### ISSUE TITLE
Warning: Each child in a list have a unique key prop warning

### ISSUE THREAD

**Issue by naskarsubhajit** [storybook-eol/react-treebeard#212]
<img width="1035" alt="Screen Shot 2019-05-08 at 6 13 22 PM" src="https://user-images.githubusercontent.com/35922462/57376303-4f9da580-71bd-11e9-8cb6-cfcf3ba2106c.png">

It looks that TreeNode component already has implementation like below:
return (
            <Ul style={style.subtree}>
                {children.map((child, index) => (
                    <TreeNode
                        {...{onToggle, animations, style}}
                        decorators={propDecorators}
                        key={child.id || index}
                        node={child}
                    />
                ))}
            </Ul>
still why it gives this warning

**Comment by YiJiangFengYun** [comment]
This is a problem of the TreeBeard, not of TreeNode.

**Comment by MorganaUzhgorod** [comment]
I have this issue too. Can anybody (@YiJiangFengYun)   help please??
I use Treebeard as commponent like this:

` 
     ...
      import { Treebeard } from 'react-treebeard';
      ...
       <Treebeard
          data={data}
          onToggle={this.onToggle}
        />
`
