### ISSUE TITLE
Update data when new file is added

### ISSUE THREAD

**Issue by nachozullo** [storybook-eol/react-treebeard#246]
First of all, thanks for the great library. 

I am implementing a library of folders and files like Google Drive. My goal is to dinamically update the treebeard when the user add or eliminate a file or folder.

It is possible?

**Comment by MattNot** [comment]
i use something like:
`
const [, reRender] = useState(false);
.
.
.
.
const update = () => {
   /* things */
  reRender(n => !n)
}
`

to force the update
